name: gigassl
channels:
  - nvidia
  - pytorch
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda
  - python=3.9
  - pytorch-cuda
  - pytorch
  - torchvision
  - conda-env
  - conda-build
  - conda-verify
  - ipdb
  - numpy
  - scipy
  - pandas
  - scikit-image
  - scikit-learn
  - matplotlib
  - seaborn
  - openslide-python
  - kornia
  - pip
  - pip:
     - intel-openmp
     - mkl
     - opencv-python
     - spams
     - staintools
